# zypper-update.yml

---
  - hosts: DEPLOY
    become: true

    vars_prompt:

      - name: "reboot_process"
        prompt: " ATTETION: reboot the hosts after update task? \n
                Type yes: "
        private: no

    roles:
      - /home/fsouza3/ansible/ardagh/roles/update_SuSE
